GET http://localhost:3000/posts 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2FiYmlyIiwiaWF0IjoxNjQ0NjE5MTM0LCJleHAiOjE2NDQ2MTkxNjl9.UcEJ0xdy_DB3tbDDJL_WOZU1ET9AX7KxsHeQDd7wmcE

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Sabbir"
}

###
POST http://localhost:3000/token 
Content-Type: application/json 

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2FiYmlyIiwiaWF0IjoxNjQ0NjIwOTAxfQ.W2FvQ5317XB73Klnrtr2Zh5AXV2b_akuzoY0a3PLF_U"
}

###
DELETE http://localhost:3000/logout
Content-Type: application/json 

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2FiYmlyIiwiaWF0IjoxNjQ0NjIwOTAxfQ.W2FvQ5317XB73Klnrtr2Zh5AXV2b_akuzoY0a3PLF_U"
}